# Generated by Django 2.2 on 2020-09-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_by',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_tasks', to='task_app.User'),
        ),
    ]
