# Generated by Django 2.2 on 2020-09-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20200913_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
